export const ErrosComuns = {
    ID_INVALIDO: "ID_INVALIDO",
  
    // NOME
    NOME_PEQUENO: "NOME_PEQUENO",
    NOME_GRANDE: "NOME_GRANDE",
    NOME_VAZIO: "NOME_VAZIO",
  
    // TEXTO
    TEXTO_VAZIO: "TEXTO_VAZIO",
    TEXTO_PEQUENO: "TEXTO_PEQUENO",
    TEXTO_GRANDE: "TEXTO_GRANDE",
  
    // DESCONHECIDO
    ERRO_DESCONHECIDO: "ERRO_DESCONHECIDO",
  } as const;
  